on:
   # https://github.com/lowlighter/metrics/blob/master/source/plugins/lines/README.md
  Leetcode:
      runs-on: ubuntu-latest
      steps:
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
